name: Keep App Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # Run every 15 minutes
  workflow_dispatch:      # Allow manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: curl -I https://yamagata-hougen.streamlit.app/
